trigger:
- master

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
  ${{ if eq( variables['Build.SourceBranchName'], 'master' ) }}:
    buildVersion: 'production'
  ${{ if eq( variables['Build.SourceBranchName'], 'develop' ) }}:
    buildVersion: 'test'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'npm install'
  workingDirectory: $(Build.SourcesDirectory)

- script: npm run build
  displayName: 'npm build'
  workingDirectory: $(Build.SourcesDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'drop/dist'
    publishLocation: 'Container'
  displayName: 'Publish $(buildVersion) artifact'

- task: CmdLine@2
- script: scp -i $(SSH_PRIVATE_KEY) $(System.DefaultWorkingDirectory)/drop/dist/ azure@79.137.39.247:/var/www/yourserver
  displayName: 'Copy dist folder via SCP'