trigger:
- master
- develop

variables:
  ${{ if eq( variables['Build.SourceBranchName'], 'master' ) }}:
    buildVersion: 'production'
    targetFolder: '/var/www/app.deposit.ovh'
  ${{ if eq( variables['Build.SourceBranchName'], 'develop' ) }}:
    buildVersion: 'test'
    targetFolder: '/var/www/app.test.deposit.ovh'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: npm install --legacy-peer-deps
  displayName: 'npm install'
  workingDirectory: $(Build.SourcesDirectory)

- script: ng test --watch=false
  displayName: 'execute test'
  workingDirectory: $(Build.SourcesDirectory)

- script: npm run build
  displayName: 'npm build'
  workingDirectory: $(Build.SourcesDirectory)

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'ssh-deposit'
    sourceFolder: '$(Build.SourcesDirectory)/dist/'
    contents: '**'
    targetFolder: '$(targetFolder)'
    readyTimeout: '20000'
